### ISSUE TITLE
Debezium Connectors Throwing EOF / Connection reset while reading bin-logs

### ISSUE THREAD

**Issue by Mahosind95** [osheroff/mysql-binlog-connector-java#15]
Hi Can you Please help up with an Issue we are facing when we are reading bin-log suddenly during high traffic we get EOF Exception/ Connection Reset Exception
**This issue we got in mysql-binlog-connector-java 0.19.0**  but i noticed that repositor is not maintained anymore, so asking here.

Read many blogs and saw the issue was caused due to Server ID but in debezium Config we have set database.server.id different for all the MySQL connectors.

Architecture : We have one server with 7 schema and we are using seven MYSQL Connectors to read the servers bin-log, with debezium whitelist property so that each connector will pass data on concerning to it's schema.

In MySQL logs we got this : **2020-09-03T09:34:35.745673Z 87255342 [Note] Aborted connection 87255342 to db: 'unconnected' user: 'kafka_source_user' host: '172.X.X.X' (Failed on my_net_write())** 

[2020-08-26 04:41:25,967] ERROR Error while deserializing binlog event at offset {ts_sec=1598429128, file=mysql-bin-changelog.179047, pos=120108368, server_id=284246538, event=394}.
Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=120174225 --stop-position=120174457 --verbose mysql-bin-changelog.179047 (io.debezium.connector.mysql.BinlogReader)
[2020-08-26 04:41:25,967] ERROR Error during binlog processing. Last offset stored = {ts_sec=1598429125, file=mysql-bin-changelog.179047, pos=114769194, row=1, server_id=284246538, event=522}, binlog reader near position = mysql-bin-changelog.179047/120174122 (io.debezium.connector.mysql.BinlogReader)
[2020-08-26 04:41:25,967] ERROR Failed due to error: Error processing binlog event (io.debezium.connector.mysql.BinlogReader)
org.apache.kafka.connect.errors.ConnectException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1598429128000, eventType=EXT_WRITE_ROWS, serverId=284246538, headerLength=19, dataLength=213, nextPosition=120174457, flags=0}
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:208)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:508)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1095)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:943)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:580)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:825)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1598429128000, eventType=EXT_WRITE_ROWS, serverId=284246538, headerLength=19, dataLength=213, nextPosition=120174457, flags=0}
	at io.debezium.connector.mysql.BinlogReader.handleServerIncident(BinlogReader.java:575)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:492)
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1598429128000, eventType=EXT_WRITE_ROWS, serverId=284246538, headerLength=19, dataLength=213, nextPosition=120174457, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223)
	at io.debezium.connector.mysql.BinlogReader$1.nextEvent(BinlogReader.java:224)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:922)
	... 3 more
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at java.io.InputStream.read(InputStream.java:170)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89)
	at io.debezium.connector.mysql.RowDeserializers.deserializeDatetimeV2(RowDeserializers.java:407)
	at io.debezium.connector.mysql.RowDeserializers$WriteRowsDeserializer.deserializeDatetimeV2(RowDeserializers.java:207)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:178)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:138)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:294)
	... 6 more
[2020-08-26 04:41:25,968] ERROR Error during binlog processing. Last offset stored = {ts_sec=1598429125, file=mysql-bin-changelog.179047, pos=114769194, row=1, server_id=284246538, event=522}, binlog reader near position = mysql-bin-changelog.179047/120174457 (io.debezium.connector.mysql.BinlogReader)

**Comment by jpechane** [comment]
@Mahosind95 Hi, would you be able to reproduce the issue and share the binary log that exhibits the issue?

**Comment by Mahosind95** [comment]
@jpechane Hi,
I am attaching the issues with bin-log events below.

**Connect Logs :**
**[2020-09-03 04:00:39,075] ERROR Error while deserializing binlog event at offset {ts_sec=1599019678, file=mysql-bin-changelog.181424, pos=18654126, server_id=284246538, event=2}**
[2020-09-03 04:00:39,075] ERROR Error during binlog processing. Last offset stored = {ts_sec=1599019675, file=mysql-bin-changelog.181424, pos=15679585, row=1, server_id=2842465XX, event=1182}, binlog reader near position = mysql-bin-changelog.181424/18654218 (io.debezium.connector.mysql.BinlogReader)
[2020-09-03 04:00:39,075] ERROR Failed due to error: Error processing binlog event (io.debezium.connector.mysql.BinlogReader)
org.apache.kafka.connect.errors.ConnectException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1599019678000, eventType=EXT_UPDATE_ROWS, serverId=2842465XX, headerLength=19, dataLength=369, nextPosition=18654736, flags=0}
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
...
...
...
Caused by: java.lang.RuntimeException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1599019678000, eventType=EXT_UPDATE_ROWS, serverId=2842465XX, headerLength=19, dataLength=369, nextPosition=18654736, flags=0}
	at io.debezium.connector.mysql.BinlogReader.handleServerIncident(BinlogReader.java:575)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:492)
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1599019678000, eventType=EXT_UPDATE_ROWS, serverId=2842465XX, headerLength=19, dataLength=369, nextPosition=18654736, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300)
..
..
..
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at java.io.InputStream.read(InputStream.java:170)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96)

--------------------------------------------------
**Bin-log File**

 @22=NULL
 @23=NULL
 @24=NULL
 @25=NULL
at 1123
200901 23:07:32 server id 284246538  end_log_pos 1154 CRC32 0x3fd49320 	Xid = 147890427821
COMMIT/*!*/;
at 1154
**200901 23:07:32 server id 284246538  end_log_pos 1219 CRC32 0x56cb6f7b 	Anonymous_GTID	last_committed=0	sequence_number=3	rbr_only=no
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;**
 at 1219
200901 23:07:32 server id 284246538  end_log_pos 1296 CRC32 0x9446a380 	Query	thread_id=85978525	exec_time=0	error_code=0
SET TIMESTAMP=1599019652/*!*/;
BEGIN
/*!*/;
 at 1296
200901 23:07:32 server id 2842465XX  end_log_pos 1389 CRC32 0x2e27d13c 	Table_map: `XXX`.`job` mapped to number 148414
 at 1389
200901 23:07:32 server id 2842465XX  end_log_pos 1577 CRC32 0x25e5122a 	Write_rows: table id 148414 flags: STMT_END_F
INSERT INTO `XXX`.`job`
SET
  @1=484978121
  @2=23421
  @3=-1 (4294967295)
  @4=3
  @5=2
  @6=70281
  @7=NULL
  @8=NULL
  @9='Job_Scheduled_aaa_20200901_230732_99

________________________________________________________
Note :
 We don;t have GTID enable on source connector

Connector Config

{
    "name": "source-prod-abc",
    "config": {
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "tasks.max": "1",
        "snapshot.mode": "schema_only_recovery",
        "snapshot.locking.mode":"none",
        "database.ssl.mode": "disabled",
        "database.ssl.keystore": "/kafka_dir/cdc_kafka_project_cluster/ssl/keystore",
        "database.ssl.keystore.password": "XXXXXX",
        "database.ssl.truststore": "/kafka_dir/cdc_kafka_project_cluster/ssl/truststore",
        "database.ssl.truststore.password": "XXXXXX",
        "database.hostname": "ZYX.com",
        "database.port": "3306",
        "database.user": "kafka_source_user",
        "database.password": "XXXXX",
        "database.server.id": "100102",
        "database.server.name": "prodabc",
        "database.whitelist": "abc",
        "database.serverTimezone": "America/Chicago",
        "database.history.kafka.bootstrap.servers": "ZYX_1.com:9092,ZYX_2:9092,ZYX_3.com:9092",
        "database.history.kafka.topic": "prod.abc.schema-changes",
        "transforms": "route",
        "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
        "transforms.route.replacement": "prodabc",
        "table.types": "TABLE,VIEW",
        "ddl.parser.mode": "antlr",
        "database.history.skip.unparseable.ddl": "true",
        "inconsistent.schema.handling.mode": "warn",
        "include.query": "true",
        "include.schema.changes": "true",
        "column.propagate.source.type": ".*",
        "time.precision.mode": "adaptive_time_microseconds",
        "numeric.mapping": "best_fit",
        "decimal.handling.mode": "double",
        "bigint.unsigned.handling.mode": "long",
	"database.history.kafka.recovery.poll.interval.ms" : "60000",
	"max.batch.size":"1024",
	"max.queue.size":"4096"
    }
}

**Comment by jpechane** [comment]
Hi, I am sorry for the misunderstanding. In this case we would need not binlog dump but the real binlog file that could be applied to a database. Maybe you'd be able to prepare a Docker container or VM with MySQL database in the state that causes DBZ to throw the exception?

I know this is a difficult task but it is super important for us so we can reproduce the issue.

**Comment by Mahosind95** [comment]
Hi @jpechane,

Sorry but it won't be possible for us to provide the Bin-logs as it from our production DB servers, and since such huge traffic is not there in non-prod we are not facing this issue.

But something we noticed would like to point out, hope you could help

We tried playing around with 

"max.batch.size:
"max.queue.size"

We increased **max.batch.size** from 1024 to 8192
We increased **max.queue.size** from 4096 to 32768

We saw that Reset Connection error increased from once in 8-10 hours to almost like every 1 hour.

So will reducing it to even lesser value that 1024  and 4096 solve the issue, or will it create some other issues if we reduce it to a very low value.

Also, some MySQL people said about : 

 **Aborted connection 87255342 to db: 'unconnected' user: 'kafka_source_user' host: '172.X.X.X' (Failed on my_net_write())**

 This error happens when the reader (deb-connector) did not consume the writes (binlog) by MySQL, this should be causing writes to fail from MySQL side.

**Comment by jpechane** [comment]
@Mahosind95 I see, so the problem is only intermittent and it does not depend on binlog content. That's good!
As you have found out the log message in MySQL log - would you be able to identify what is first? If the error message on server and then Debezium failuer or vice versa?

**Comment by Mahosind95** [comment]
@jpechane 
Hi We are suspecting that issue is due to Amazone EFS {possibility}

So In our setup we have a three VM cluster and the have a shared EFS drive mounted on them (We went with this approach as we where having disk space issue as we were adding new connectors every time).

We created kafka/ip folder inside the efs drive 
and configured the kafka log directory respective in the individual VM(s) properties file.

Add now since we have 17 bin-log (debezium connectors) distributed over 3 VM(s) and all writing to the same disk, we are think it's causing delay and in the mean time the MySQL is timing out the connection.

Also we noticed increase in number of issue like 

1) The database history couldn't be recovered. Consider to increase the value for database.history.kafka.recovery.poll.interval.ms 
2)  Failed to get offsets by times in 30003ms

Would be great if you could suggest something/ Or if could add more to our analysis and help us solve it.

**Comment by wkhapy123** [comment]
did issue fix

**Comment by ismailsimsek** [comment]
@Mahosind95 did you find a way to fix the issue?  Getting same error and restarting debezium passes the parsing error. 
failures are usually happening after high load on the source database

**Comment by Mahosind95** [comment]
@ismailsimsek . No we didn't find any solution to this. We had around 40 connectors writing to the same EFS disk and hence we came to a conclusion that the connector are spending to much time waiting to write data into topics till then the DB Server is killing the connection. We reduced the number of connectors to 8, and  we saw a significant drop in the number of issues.

Perviously we used to get 4-5 issues a day.
now we get 4-5 issues a month and we have scripts to restart the connectors.

We have a hunch it was due to the write speed of the source connectors on the disk. But we are not sure.
Hope it helps you. Please post here if you find a permanent fix.

**Comment by ismailsimsek** [comment]
Thank you @Mahosind95 for sharing details

i see most of the times exception happens after this INFO line, printed by following code
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L797

printing info log [here](https://github.com/osheroff/mysql-binlog-connector-java/blob/96edcd5feaf208559cae4a4b44a49d9ab96df5d4/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L786) could give more details about what is happening, it could help to see why/how connectionLost sets to True

**Comment by osheroff** [comment]
@ismailsimsek feel free to post your logs

**Comment by ismailsimsek** [comment]
@osheroff our case we observed similar situation

- with the custom debezium consumer, we have `Thread.sleep` inside `handleBatch` to increase batch size. it could wait up to 5 minutes (db slave_net_timeout is 60 seconds)
- and source database has batch processing which periodically gets increased load (insert update etc)
- most of the errors happens after increased load at the source database

after changing sleep wait/strategy inside consumer we are not experiencing the error so far
new waiting strategy is monitoring debezium-queue size(from metrics) and consuming it when it reaches max batch size
