### ISSUE TITLE
Can't read from binlog of mysql hosted by azure when ssl enabled

### ISSUE THREAD

**Issue by cubbuk** [osheroff/mysql-binlog-connector-java#18]
We are trying to use debezium read changes from a mysql instance hosted on Azure.

We have realized that when ssl is enabled, we get an authentication error while trying to read binlog. Sample error stack trace is as below:

```
connect_1  |    at io.debezium.connector.mysql.BinlogReader.doStart(BinlogReader.java:445)
connect_1  |    at io.debezium.connector.mysql.AbstractReader.start(AbstractReader.java:116)
connect_1  |    at io.debezium.connector.mysql.ChainedReader.startNextReader(ChainedReader.java:206)
connect_1  |    at io.debezium.connector.mysql.ChainedReader.readerCompletedPolling(ChainedReader.java:158)
connect_1  |    at io.debezium.connector.mysql.AbstractReader.cleanupResources(AbstractReader.java:309)
connect_1  |    at io.debezium.connector.mysql.AbstractReader.poll(AbstractReader.java:288)
connect_1  |    at io.debezium.connector.mysql.ChainedReader.poll(ChainedReader.java:146)
connect_1  |    at io.debezium.connector.mysql.MySqlConnectorTask.doPoll(MySqlConnectorTask.java:443)
connect_1  |    at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:131)
connect_1  |    at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
connect_1  |    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
connect_1  |    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
connect_1  |    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
connect_1  |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect_1  |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect_1  |    at java.base/java.lang.Thread.run(Thread.java:834)
connect_1  | Caused by: java.io.EOFException
connect_1  |    at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
connect_1  |    at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
connect_1  |    at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.read(PacketChannel.java:59)
connect_1  |    at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:722)
connect_1  |    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:515)
connect_1  |    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:860)
connect_1  |    ... 1 more
```

This is most probably related to not passing authority certificate issue. Nevertheless since we don't get any authorization exception during snapshot phase, this error becomes very confusing for us. Is there any option to by pass this error without passing certificate file?

**Comment by osheroff** [comment]
can you give the debezium (and mysql-binlog-connector-java) version used?  Azure does some weird stuff at the network level that we've worked around in various ways in the past, this may be another instance of it, or....

**Comment by cubbuk** [comment]
We are using version 1.2 for debezium and mysql 8. Thanks for the help.

**Comment by osheroff** [comment]
this should have been fixed by https://github.com/osheroff/mysql-binlog-connector-java/pull/27.  Not sure if/when debezium will pull it into their release.
