### ISSUE TITLE
The connector does not work with Proxysql >= 2.1.0

### ISSUE THREAD

**Issue by tinntsea** [osheroff/mysql-binlog-connector-java#44]
Hi,

I've upgraded Proxysql from 2.0.18 to 2.1.0 and the connector stopped working. It works well when I downgrade Proxysql back to 2.0.18

```
mysql_connector_1           | Jul 02, 2021 10:00:53 AM com.github.shyiko.mysql.binlog.BinaryLogClient$2 run
mysql_connector_1           | WARNING: Failed to establish connection in 29998ms. Forcing disconnect.

mysql_connector_1           | 	at io.debezium.connector.mysql.BinlogReader.doStart(BinlogReader.java:435)
mysql_connector_1           | 	at io.debezium.connector.mysql.AbstractReader.start(AbstractReader.java:116)
mysql_connector_1           | 	at io.debezium.connector.mysql.ChainedReader.startNextReader(ChainedReader.java:206)
mysql_connector_1           | 	at io.debezium.connector.mysql.ChainedReader.start(ChainedReader.java:103)
mysql_connector_1           | 	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:279)
mysql_connector_1           | 	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106)
mysql_connector_1           | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
mysql_connector_1           | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
mysql_connector_1           | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
mysql_connector_1           | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
mysql_connector_1           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
mysql_connector_1           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
mysql_connector_1           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
mysql_connector_1           | 	at java.base/java.lang.Thread.run(Thread.java:834)
mysql_connector_1           | Caused by: java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 30000ms
mysql_connector_1           | 	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:862)
mysql_connector_1           | 	at io.debezium.connector.mysql.BinlogReader.doStart(BinlogReader.java:407)
mysql_connector_1           | 	... 13 more
mysql_connector_1           | 2021-07-02 10:00:53,260 ERROR  ||  WorkerSourceTask{id=my-mysql-connector-0} Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
```

Here is the logs from Proxysql container:

```
proxysql1_1                 | 2021-07-02 10:00:53 MySQL_Thread.cpp:4838:process_all_sessions(): [WARNING] Closing unhealthy client connection 172.28.1.17:47360
```

You can check the Proxysql changelogs at https://github.com/sysown/proxysql/releases/tag/v2.1.0

**Comment by osheroff** [comment]
did you solve this?  or are you simply closing the issue?

**Comment by tinntsea** [comment]
Hi Osheroff,

Looks like the issue is on ProxySQL as we faced the same issue with other mysql binlog connector libs. That's why I closed the issue.

But I will update the root cause & solution here once we found it.

**Comment by tinntsea** [comment]
Hi, I want to give an update on the issue.
ProxySQL >= 2.1 supports CLIENT_DEPRECATE_EOF, while the lower versions don't. Which somehow triggered https://bugs.mysql.com/bug.php?id=83346.
So to fix the issue we need to add following parameters to proxysql config

```mysql_variables=
{
    enable_server_deprecate_eof=false
    enable_client_deprecate_eof=false
}```

Related issue https://github.com/sysown/proxysql/issues/3251
