### ISSUE TITLE
Test failure with MySQL 8.0

### ISSUE THREAD

**Issue by gunnarmorling** [osheroff/mysql-binlog-connector-java#46]
The test `com.github.shyiko.mysql.binlog.BinaryLogClientIntegrationTest.testDeserializationOfYEAR()` fails with MySQL 8.0:

```
INFO: Received Event{header=EventHeaderV4{timestamp=1626463811000, eventType=QUERY, serverId=1, headerLength=19, dataLength=56, nextPosition=3236, flags=8}, data=QueryEventData{threadId=10, executionTime=0, errorCode=0, database='mbcj_test', sql='BEGIN'}}
Jul 16, 2021 7:30:11 PM com.github.shyiko.mysql.binlog.TraceLifecycleListener onEventDeserializationFailure
SEVERE: Event deserialization failed
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1626463811000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=59, nextPosition=3314, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:952)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Unsupported table metadata field type: 128
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:47)
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:47)
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:1)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
	... 6 more
```

No idea where this metadata type 128 is coming from, I don't see it documented anywhere.

Which makes me think: perhaps we should handle unexpected metadata types more gracefully, rather logging a warning instead of throwing an exception? Adhering to "Be conservative with what you send and relaxed with what you receive", we might simply ignore this case. WDYT, @osheroff!

**Comment by gunnarmorling** [comment]
Turns out this is only occurring when using binlog-row-metadata=FULL; I've taken care of it in my PR for #40. Will close this therefore.
