### ISSUE TITLE
Deserialize table map metadata failed with java.io.EOFException: Failed to read next byte from position 15

### ISSUE THREAD

**Issue by harveyyue** [osheroff/mysql-binlog-connector-java#74]
The optional table metadata is not sorted, when reading the type UNKNOWN_METADATA_FIELD_TYPE not in the end position cause this issue.

**Refer mysql rows_event code:** 
https://github.com/mysql/mysql-server/blob/8.0/libbinlogevents/include/rows_event.h#L185

> There are some optional metadata defined. They are listed in the table
    @ref Table_table_map_event_optional_metadata. Optional metadata fields
    follow null_bits. Whether binlogging an optional metadata is decided by the
    server. The order is not defined, so they can be binlogged in any order.

**Related sql statement:**
`create table workdb.`debezium_all_types` (
`id` int(11) not null auto_increment,
`tinyi` tinyint(4) default '0',
`smalli` smallint(6) default '0',
`mediumi` mediumint(9) default '0',
`bigi` bigint(20) default '0',
`f` float default '0.001',
`dou` double default '0',
`de` decimal(36,2) default '0.00',
`c` char(10) collate utf8_bin default 'char',
`v` varchar(255) collate utf8_bin default 'varchar',
`te` text collate utf8_bin,
`tinyt` tinytext collate utf8_bin,
`mediumt` mediumtext collate utf8_bin,
`longt` longtext collate utf8_bin,
`b` blob,
`tinyb` tinyblob,
`mediumb` mediumblob,
`longb` longblob,
`d` date default null,
`t` time not null default '18:30:30',
`dt` datetime default null,
`ts` timestamp not null default current_timestamp,
`y` year(4) default '2000',
primary key (`id`)
) engine=innodb auto_increment=1 default charset=utf8 collate=utf8_bin;`
INSERT INTO workdb.debezium_all_types_2 (tinyi,mediumi,bigi,f,dou,de,c,v,te,tinyt,mediumt,longt,b,tinyb,mediumb,longb,d,t,dt,ts,y) 
VALUES (127, 8388607, 225073858, 1.17549435138, 2.225073858, 12345678910111213141516.17, 'Maria', 'Maria carchar', 'Maria text', 'Maria tiny text', 'Maria medium text', 'Maria long text', 65534, 65534, 16777214, 4294967294, now(), now(), now(), now(), '2022');

**Debezium error log:**
`Trace:      org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50)
at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1233)
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:980)
at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599)
at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857)
at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1655558927000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=104, nextPosition=7697425, flags=0}
at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1188)
... 5 more
  Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1655558927000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=104, nextPosition=7697425, flags=0}
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309)
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281)
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228)
at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:230)
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:952)
... 3 more
  Caused by: java.io.EOFException: Failed to read next byte from position 15
at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:213)
at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readPackedNumber(ByteArrayInputStream.java:173)
at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readPackedInteger(ByteArrayInputStream.java:152)
at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.readIntegerPairs(TableMapEventMetadataDeserializer.java:164)
at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:86)
at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:47)
at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:27)
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
... 7 more`

**Comment by harveyyue** [comment]
close it with fixed.
