### ISSUE TITLE
java.io.EOFException when reading large number of UPDATE events

### ISSUE THREAD

**Issue by jogrogan** [osheroff/mysql-binlog-connector-java#93]
We have had a setup using this library for a while now with no issues. However we recently found a deserialization issue when attempting to read a large number of UPDATE events under one transaction from the binlog.

Setup:
We have a DB with a column for each MySQL column type (33 columns).
When performing an update across a large number of these rows (1000+) we begin seeing the below exception.

Sample Update to update all rows:
UPDATE test_table SET smallint_column = 10;

Exception:
```java
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1671468952000, eventType=EXT_UPDATE_ROWS, serverId=190225211, headerLength=19, dataLength=83
87, nextPosition=21497348, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:335) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:238) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:949) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:854) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.io.EOFException: Failed to read remaining 10476 of 14390 bytes from position 5409623. Block length: 0. Initial block length: 8383.
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:115) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:105) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeBlob(AbstractRowsEventDataDeserializer.java:403) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:199) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:143) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:71) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:329) ~[mysql-binlog-connector-java-0.26.1.jar:0.26.1]
        ... 5 more
```

Additional Observations:
- When updating >1000 rows the exception happens consistently.
- When updating ~100 rows the exception happens inconsistently. Sometimes it happens, sometimes on restart/reconnection it passes.
- Our event listener successfully receives the GTID event, QUERY event, TABLE_MAP event, followed by sometimes the first few EXT_UPDATE_ROWS events associated with this transaction before failure.
- It is not consistent in failing inside of `deserializeBlob`. I have tried removing this column all together and have seen the same issue coming from `deserializeJson` and `deserializeNewDecimal`.

The difference I have noticed so far is that in the failed events the `len` param in [readWithinBlockBoundaries(...)](https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java#L266) exceeds the `blockLength`. So all bytes are read that are left in the `blockLength` but any remaining bytes `len - blockLength` are not, and fail with the corresponding offsets printed in the exception above.

Binlog library version: 0.26.1
MySQL version: 8.0.28

**Comment by osheroff** [comment]
do you think you could put together a script that generates data that might trigger the condition?

**Comment by jogrogan** [comment]
@osheroff here is the setup and sample record generation


**Table Creation:**
```sql
CREATE TABLE `test_table` (
`int_column` int NOT NULL AUTO_INCREMENT,
`varchar_column` varchar(20) DEFAULT NULL,
`tinyint_column` tinyint DEFAULT NULL,
`text_column` text,
`date_column` date DEFAULT NULL,
`smallint_column` smallint DEFAULT NULL,
`mediumint_column` mediumint DEFAULT NULL,
`bigint_column` bigint DEFAULT NULL,
`float_column` float(10,2) DEFAULT NULL,
`double_column` double DEFAULT NULL,
`decimal_column` decimal(10,2) DEFAULT NULL,
`datetime_column` datetime DEFAULT NULL,
`timestamp_column` timestamp NULL DEFAULT NULL,
`time_column` time DEFAULT NULL,
`year_column` year DEFAULT NULL,
`char_column` char(10) DEFAULT NULL,
`tinyblob_column` tinyblob,
`tinytext_column` tinytext,
`blob_column` blob,
`mediumblob_column` mediumblob,
`mediumtext_column` mediumtext,
`longblob_column` longblob,
`longtext_column` longtext,
`enum_column` enum('c','b','a') DEFAULT NULL,
`set_column` set('c','b','a') DEFAULT NULL,
`bool_column` tinyint(1) DEFAULT NULL,
`binary_column` binary(20) DEFAULT NULL,
`varbinary_column` varbinary(20) DEFAULT NULL,
`numeric_column` decimal(10,3) DEFAULT NULL,
`json_column` json DEFAULT NULL,
`ETL_TS` datetime(6) DEFAULT CURRENT_TIMESTAMP(6),
`DELETED_TS` datetime(6) DEFAULT NULL,
`int_column_unsigned` int unsigned DEFAULT NULL,
PRIMARY KEY (`int_column`)
) ENGINE=InnoDB AUTO_INCREMENT=41961 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```


**Insert Record:**
```bash
$ cat insert.sh

varchar_column=`openssl rand -hex 10`
tinyint_column=10
text_column=`openssl rand -hex 100`
date_column='2022-11-06'
smallint_column=200
mediumint_column=5000
bigint_column=70000
float_column=34343232.9872
double_column=45454.23
decimal_column=2323232.46563
datetime_column='1000-01-01 00:01:00'
timestamp_column='2022-01-01 00:00:01'
time_column='00:01:00'
year_column='2022'
char_column='abcdefghij'
tinyblob_column=`openssl rand -hex 100`
tinytext_column=`openssl rand -hex 100`
blob_column=`openssl rand -hex 500`
mediumblob_column=`openssl rand -hex 200`
mediumtext_column=`openssl rand -hex 300`
longblob_column=`openssl rand -hex 700`
longtext_column=`openssl rand -hex 600`
enum_column=$1
set_column=$2
bool_column='0'
binary_column=`openssl rand -hex 10`
varbinary_column=`openssl rand -hex 10`
numeric_column=10
json_column='{"continent": "South America", "population": "656877765"}'

echo "insert into test_table (varchar_column, tinyint_column, text_column, date_column, smallint_column, mediumint_column, bigint_column, float_column, double_column, decimal_column, datetime_column, timestamp_column, time_column, year_column, char_column, tinyblob_column, tinytext_column, blob_column, mediumblob_column, mediumtext_column, longblob_column, longtext_column, enum_column, set_column, bool_column, binary_column, varbinary_column, numeric_column, json_column) values
('$varchar_column',
$tinyint_column,
'$text_column',
'$date_column',
'$smallint_column',
'$mediumint_column',
'$bigint_column',
'$float_column',
'$double_column',
'$decimal_column' ,
'$datetime_column',
'$timestamp_column',
'$time_column',
'$year_column',
'$char_column',
'$tinyblob_column',
'$tinytext_column',
'$blob_column',
'$mediumblob_column',
'$mediumtext_column',
'$longblob_column',
'$longtext_column',
'$enum_column',
'$set_column',
'$bool_column',
'$binary_column',
'$varbinary_column',
'$numeric_column',
'$json_column ');"
```


**Loop to insert 2000 records:**
```bash
$ cat loop.sh

for i in {1..2000};
do

./insert.sh a b >> insert.sql

done
```

$ ./loop.sh
$ mysql -u root -p test_db < insert.sql > insert.log

**Update to trigger EOFException:**
```sql
UPDATE test_table SET smallint_column = 100;
```

**Comment by osheroff** [comment]
ok, I couldn't repro.  I tried this with:

- maxwell, using a more recent binlog-connector (but I don't think the version of binlog-connector matters)
- mysql 0.8.30 (I suppose it could matter?)

Is it possible to distill some java code that repros the issue?  Can you repro the issue on any mysql server (eg docker) or is it special in production?  Also please post your mysql server config.

**Comment by jogrogan** [comment]
Have only been seeing this issue in production so far, but don't have a local setup to test on.
I spent the last day setting up maxwell against our DB and maxwell seems to process the events fine. Trying to upgrade to the more recent binlog-connector and look at the difference in setups between ours and maxwell. Will report back soon

**Comment by osheroff** [comment]
k.  the more recent binlog-connector really shouldn't change anything as far as I can see.  maybe there's something with an event deserializer or configuration setup that maxwell avoids.  dunno!

**Comment by jogrogan** [comment]
Looks like the issue was indeed on our end. We had some logic that changed some info in the TableMapEvent which caused subsequent deserialization problems upstream since the object was the same in memory.

Will close the issue

**Comment by osheroff** [comment]
cool, glad you found the root cause.
